# Generated by Django 6.0 on 2025-12-28 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('tokens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('session', 'token_number'), ('user', 'session')},
        ),
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
